__version__: 27
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 2.83
        Brightness: 2.5
        ExposureTime: 1000
        Gain: 1.5
  Color:
    __version__: 7
    Settings2D:
      Acquisitions:
        - Acquisition:
            Aperture: 2.83
            Brightness: 2.5
            ExposureTime: 1000
            Gain: 2
      Processing:
        Color:
          Balance:
            Blue: 1
            Green: 1
            Red: 1
          Experimental:
            Mode: automatic
          Gamma: 1
      Sampling:
        Color: rgb
        Pixel: by4x4
  Diagnostics:
    Enabled: no
  Engine: phase
  Processing:
    Color:
      Balance:
        Blue: __not_set__
        Green: __not_set__
        Red: __not_set__
      Experimental:
        Mode: __not_set__
      Gamma: __not_set__
    Filters:
      Cluster:
        Removal:
          Enabled: yes
          MaxNeighborDistance: 4
          MinArea: 300
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: no
            Strength: 0.2
          Removal:
            Enabled: no
            Threshold: 0.2
      Hole:
        Repair:
          Enabled: no
          HoleSize: 0.4
          Strictness: 1
      Noise:
        Removal:
          Enabled: yes
          Threshold: 2
        Repair:
          Enabled: yes
        Suppression:
          Enabled: yes
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 5
      Reflection:
        Removal:
          Enabled: yes
          Mode: global
      Smoothing:
        Gaussian:
          Enabled: no
          Sigma: 0.75
    Resampling:
      Mode: disabled
  RegionOfInterest:
    Box:
      Enabled: no
      Extents: [-10, 100]
      PointA: [0, 0, 0]
      PointB: [0, 0, 0]
      PointO: [0, 0, 0]
    Depth:
      Enabled: no
      Range: [300, 1100]
  Sampling:
    Color: __not_set__
    Pixel: by4x4
